"""create tables

Revision ID: 7a1ba5ef935b
Revises: 
Create Date: 2024-07-18 18:37:38.168904

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7a1ba5ef935b"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("username", sa.TEXT(), nullable=False),
        sa.Column("password_hash", sa.TEXT(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__user")),
        sa.UniqueConstraint("id", name=op.f("uq__user__id")),
    )
    op.create_index(
        op.f("ix__user__password_hash"), "user", ["password_hash"], unique=False
    )
    op.create_index(op.f("ix__user__username"), "user", ["username"], unique=True)
    op.create_table(
        "note",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("note_text", sa.TEXT(), nullable=False),
        sa.Column("comment", sa.TEXT(), nullable=True),
        sa.Column("url", sa.TEXT(), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["user.id"], name=op.f("fk__note__owner_id__user")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__note")),
        sa.UniqueConstraint("id", name=op.f("uq__note__id")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("note")
    op.drop_index(op.f("ix__user__username"), table_name="user")
    op.drop_index(op.f("ix__user__password_hash"), table_name="user")
    op.drop_table("user")
    # ### end Alembic commands ###
